version: '3.7'

services:
  user_api:
    image: user_api
    env_file:
      - ./env/local.env
    #    volumes:
    #      - './env/local.config.yaml:/config.yaml'
    ports:
      - '80:80'
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "./app", "check"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      scaffold:

  mongo:
    image: mongo:3
    env_file:
      - ./env/local.env
    ports:
      - '27017:27017'
    networks:
      scaffold:

volumes:
  postgres_data: {}

networks:
  scaffold: {}
