version: '3.7'

services:
  user_api:
    image: user_api
    env_file:
      - ./env/local.env
#    volumes:
#      - './env/local.config.yaml:/config.yaml'
    ports:
      - '80:80'
    depends_on:
      - postgres
      - couchdb
      - nats
    healthcheck:
      test: ["CMD", "./app", "check"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      scaffold:

  couchdb:
    image: couchdb:3
    env_file:
      - ./env/local.env
    volumes:
      - couchdb_data:/opt/couchdb/data
    ports:
      # for web ui go to http://127.0.0.1:5984/_utils
      - '5984:5984'
    networks:
      scaffold:

volumes:
  postgres_data: {}

networks:
  scaffold: {}
