dev_mode: true
services_init_timeout: 15 # in seconds

api:
  host: 0.0.0.0
  port: 80
  dev_mode: true
  enable_cors: true
  api_request_timeout: 60

log:
  app_name: user_api
  level: env:LOG_LEVEL
  add_trace: true
  sentry: ""
  json: false

mongo:
  host: 127.0.0.1
  port: 27017
  database: user_api
#  username: env:MONGO_INITDB_ROOT_USERNAME
#  password: env:MONGO_INITDB_ROOT_PASSWORD
